import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DetectionResult } from '@/lib/ai/detection';
import { getDiseaseTranslation } from '@/lib/disease-translations';

const COLORS = {
  primary: [22, 163, 74] as [number, number, number],
  secondary: [21, 128, 61] as [number, number, number],
  accent: [74, 222, 128] as [number, number, number],
  surface: [220, 252, 231] as [number, number, number],
  text: [31, 41, 55] as [number, number, number],
  textLight: [107, 114, 128] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  danger: [220, 38, 38] as [number, number, number],
  warning: [245, 158, 11] as [number, number, number],
  success: [22, 163, 74] as [number, number, number],
  yellow: [254, 252, 232] as [number, number, number],
  orange: [245, 158, 11] as [number, number, number],
};

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function getSeverityColor(severity: number): number[] {
  if (severity >= 7) return COLORS.danger;
  if (severity >= 5) return COLORS.warning;
  return COLORS.success;
}

// PDF Translations
const PDF_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    title: 'PLANT DISEASE DETECTION REPORT',
    reportId: 'REPORT ID',
    generated: 'GENERATED',
    diseaseInfo: 'DISEASE INFORMATION',
    diseaseName: 'Disease Name',
    confidence: 'Confidence',
    severity: 'Severity',
    affectedArea: 'Affected Area',
    cropType: 'Crop Type',
    analysisResults: 'ANALYSIS RESULTS',
    qualityMetrics: 'Quality Metrics',
    imageQuality: 'Image Quality',
    detectionSpeed: 'Detection Speed',
    treatmentRecommendations: 'TREATMENT RECOMMENDATIONS',
    organic: 'Organic Treatments',
    chemical: 'Chemical Treatments',
    cultural: 'Cultural Practices',
    prevention: 'Prevention Measures',
    importantNotes: 'IMPORTANT NOTES',
    disclaimer: 'Disclaimer',
    disclaimerText: 'This report is generated by AI and should be used as a reference only. For critical decisions, please consult with agricultural experts.',
    footer: 'Generated by AgriSakhi - AI-Powered Plant Disease Detection',
    high: 'High',
    moderate: 'Moderate',
    low: 'Low'
  },
  hi: {
    title: 'पौध रोग पहचान रिपोर्ट',
    reportId: 'रिपोर्ट आईडी',
    generated: 'उत्पन्न',
    diseaseInfo: 'रोग जानकारी',
    diseaseName: 'रोग का नाम',
    confidence: 'विश्वास',
    severity: 'गंभीरता',
    affectedArea: 'प्रभावित क्षेत्र',
    cropType: 'फसल प्रकार',
    analysisResults: 'विश्लेषण परिणाम',
    qualityMetrics: 'गुणवत्ता मेट्रिक्स',
    imageQuality: 'छवि गुणवत्ता',
    detectionSpeed: 'पहचान गति',
    treatmentRecommendations: 'उपचार सिफारिशें',
    organic: 'जैविक उपचार',
    chemical: 'रासायनिक उपचार',
    cultural: 'सांस्कृतिक अभ्यास',
    prevention: 'रोकथाम उपाय',
    importantNotes: 'महत्वपूर्ण नोट्स',
    disclaimer: 'अस्वीकरण',
    disclaimerText: 'यह रिपोर्ट एआई द्वारा उत्पन्न की गई है और केवल संदर्भ के रूप में उपयोग की जानी चाहिए। महत्वपूर्ण निर्णयों के लिए, कृपया कृषि विशेषज्ञों से परामर्श लें।',
    footer: 'अग्रीसखी द्वारा उत्पन्न - एआई-संचालित पौध रोग पहचान',
    high: 'उच्च',
    moderate: 'मध्यम',
    low: 'कम'
  },
  kn: {
    title: 'ಸಸ್ಯ ರೋಗ ಪತ್ತೆ ವರದಿ',
    reportId: 'ವರದಿ ಐಡಿ',
    generated: 'ರಚಿಸಲಾಗಿದೆ',
    diseaseInfo: 'ರೋಗ ಮಾಹಿತಿ',
    diseaseName: 'ರೋಗದ ಹೆಸರು',
    confidence: 'ವಿಶ್ವಾಸ',
    severity: 'ತೀವ್ರತೆ',
    affectedArea: 'ಪರಿಣಾಮಿತ ಪ್ರದೇಶ',
    cropType: 'ಬೆಳೆ ಪ್ರಕಾರ',
    analysisResults: 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು',
    qualityMetrics: 'ಗುಣಮಟ್ಟದ ಮಾಪನಗಳು',
    imageQuality: 'ಚಿತ್ರ ಗುಣಮಟ್ಟ',
    detectionSpeed: 'ಪತ್ತೆ ವೇಗ',
    treatmentRecommendations: 'ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸುಗಳು',
    organic: 'ಸಾವಯವ ಚಿಕಿತ್ಸೆಗಳು',
    chemical: 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆಗಳು',
    cultural: 'ಸಾಂಸ್ಕೃತಿಕ ಅಭ್ಯಾಸಗಳು',
    prevention: 'ತಡೆಗಟ್ಟುವ ಕ್ರಮಗಳು',
    importantNotes: 'ಪ್ರಮುಖ ಟಿಪ್ಪಣಿಗಳು',
    disclaimer: 'ಹಕ್ಕುತ್ಯಾಗ',
    disclaimerText: 'ಈ ವರದಿಯನ್ನು AI ನಿಂದ ರಚಿಸಲಾಗಿದೆ ಮತ್ತು ಇದನ್ನು ಕೇವಲ ಉಲ್ಲೇಖವಾಗಿ ಬಳಸಬೇಕು। ನಿರ್ಣಾಯಕ ನಿರ್ಧಾರಗಳಿಗೆ, ದಯವಿಟ್ಟು ಕೃಷಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ।',
    footer: 'ಅಗ್ರಿಸಖಿಯಿಂದ ರಚಿಸಲಾಗಿದೆ - AI-ಚಾಲಿತ ಸಸ್ಯ ರೋಗ ಪತ್ತೆ',
    high: 'ಹೆಚ್ಚು',
    moderate: 'ಮಧ್ಯಮ',
    low: 'ಕಮ್ಮಿ'
  },
  ur: {
    title: 'پودوں کی بیماری کی تشخیص رپورٹ',
    reportId: 'رپورٹ ID',
    generated: 'تخلیق کیا گیا',
    diseaseInfo: 'بیماری کی معلومات',
    diseaseName: 'بیماری کا نام',
    confidence: 'اعتماد',
    severity: 'شدت',
    affectedArea: 'متاثرہ علاقہ',
    cropType: 'فصل کی قسم',
    analysisResults: 'تجزیہ کے نتائج',
    qualityMetrics: 'معیار کی میٹرکس',
    imageQuality: 'تصویر کا معیار',
    detectionSpeed: 'تشخیص کی رفتار',
    treatmentRecommendations: 'علاج کی سفارشات',
    organic: 'نامیاتی علاج',
    chemical: 'کیمیکل علاج',
    cultural: 'ثقافتی طریقے',
    prevention: 'روک تھام کے اقدامات',
    importantNotes: 'اہم نوٹس',
    disclaimer: 'اعلان برائت',
    disclaimerText: 'یہ رپورٹ AI کے ذریعے تیار کی گئی ہے اور صرف حوالہ کے طور پر استعمال کی جانی چاہیے۔ اہم فیصلوں کے لیے، براہ کرم زرعی ماہرین سے مشورہ کریں۔',
    footer: 'AgriSakhi کے ذریعے تیار کردہ - AI سے چلنے والی پودوں کی بیماری کی تشخیص',
    high: 'زیادہ',
    moderate: 'معتدل',
    low: 'کم'
  }
};

export async function generatePDFReport(result: DetectionResult, _imageUrl?: string, language: string = 'en'): Promise<void> {
  const t = PDF_TRANSLATIONS[language] || PDF_TRANSLATIONS.en;
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  let yPos = 0;

  // ============ HEADER WITH GRADIENT ============
  for (let i = 0; i < 35; i++) {
    const opacity = 1 - (i / 35) * 0.12;
    pdf.setFillColor(
      Math.max(0, COLORS.primary[0] - i * 0.15),
      Math.max(0, COLORS.primary[1] - i * 0.15),
      Math.max(0, COLORS.primary[2] - i * 0.15)
    );
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (pdf as any).setGState(new (pdf as any).GState({ opacity }));
    pdf.rect(0, i, pageWidth, 1, 'F');
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (pdf as any).setGState(new (pdf as any).GState({ opacity: 1 }));

  // Top accent
  pdf.setFillColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
  pdf.rect(0, 0, pageWidth, 1.5, 'F');

  // Logo - simple circle, NO weird characters
  pdf.setFillColor(COLORS.white[0], COLORS.white[1], COLORS.white[2]);
  pdf.circle(23, 17, 9, 'F');
  
  // Draw leaf manually instead of emoji
  pdf.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.setLineWidth(0.3);
  // Simple leaf shape
  pdf.ellipse(23, 17, 4, 6, 'F');
  pdf.setDrawColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.line(23, 11, 23, 23);

  // Brand text - CLEAN, no special chars
  pdf.setTextColor(COLORS.white[0], COLORS.white[1], COLORS.white[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(26);
  pdf.text('AgriSakhi', 37, 16);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(t.title, 37, 22);

  // Metadata box
  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'bold');
  const reportId = `RPT-${Date.now().toString(36).toUpperCase()}`;
  pdf.text(t.reportId, pageWidth - 58, 10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(reportId, pageWidth - 58, 14);
  
  pdf.setFont('helvetica', 'bold');
  pdf.text(t.generated, pageWidth - 58, 18);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6.5);
  const dateStr = formatDate(new Date());
  const dateLines = pdf.splitTextToSize(dateStr, 48);
  pdf.text(dateLines, pageWidth - 58, 22);

  yPos = 38;

  // ============ DETECTION CARD ============
  pdf.setFillColor(COLORS.surface[0], COLORS.surface[1], COLORS.surface[2]);
  pdf.roundedRect(14, yPos, pageWidth - 28, 32, 3, 3, 'F');
  
  pdf.setDrawColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.setLineWidth(0.8);
  pdf.roundedRect(14, yPos, pageWidth - 28, 32, 3, 3, 'S');

  yPos += 8;

  pdf.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8.5);
  pdf.text(t.diseaseInfo.toUpperCase(), 18, yPos);

  yPos += 7;

  pdf.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  const diseaseName = getDiseaseTranslation(result.disease, language);
  const diseaseLines = pdf.splitTextToSize(diseaseName, pageWidth - 40);
  pdf.text(diseaseLines, 18, yPos);

  yPos += diseaseLines.length * 7 + 3;

  const confidencePercent = Math.round(result.confidence * 100);
  const badgeWidth = 30;
  const badgeX = pageWidth - 18 - badgeWidth;
  const badgeY = yPos - 5;

  // Confidence badge
  pdf.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.roundedRect(badgeX, badgeY, badgeWidth, 9, 4.5, 4.5, 'F');
  pdf.setTextColor(COLORS.white[0], COLORS.white[1], COLORS.white[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9.5);
  pdf.text(`${confidencePercent}% ${t.confidence}`, badgeX + badgeWidth/2, badgeY + 4, { align: 'center' });

  // Severity badge
  const severityColor = getSeverityColor(result.severity) as [number, number, number];
  pdf.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
  pdf.roundedRect(18, yPos - 5, 32, 9, 4.5, 4.5, 'F');
  pdf.text(`Severity ${result.severity}/10`, 20, yPos);

  yPos += 15;

  // ============ METRICS TABLE ============
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(13);
  pdf.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  pdf.text(t.analysisResults, 14, yPos);
  
  pdf.setDrawColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
  pdf.setLineWidth(2);
  pdf.line(14, yPos + 1.5, 70, yPos + 1.5);
  
  yPos += 5;

  const metricsData = [
    ['Metric', 'Value', 'Status'],
    ['Confidence', `${confidencePercent}%`, confidencePercent >= 80 ? 'High' : 'Moderate'],
    ['Severity', `${result.severity}/10`, result.severity >= 7 ? 'Critical' : 'Manageable'],
    ['Affected Area', `${Math.round(result.affectedArea)}%`, result.affectedArea >= 50 ? 'Large' : 'Moderate'],
    ['Image Quality', `${result.metadata.imageQuality}%`, 'Good'],
    ['Time', `${result.metadata.inferenceTime}ms`, 'Fast'],
  ];

  autoTable(pdf, {
    startY: yPos,
    head: [metricsData[0]],
    body: metricsData.slice(1),
    theme: 'grid',
    tableWidth: pageWidth - 28,
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      halign: 'center',
      fontSize: 9.5,
      cellPadding: 2.5,
    },
    bodyStyles: {
      textColor: COLORS.text,
      fontSize: 8.5,
      cellPadding: 2.5,
    },
    alternateRowStyles: {
      fillColor: COLORS.surface,
    },
    columnStyles: {
      0: { fontStyle: 'bold' },
      1: { halign: 'center', fontStyle: 'bold' },
      2: { halign: 'center', textColor: COLORS.primary, fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
    styles: {
      lineColor: [200, 200, 200],
      lineWidth: 0.1,
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  yPos = (pdf as any).lastAutoTable.finalY + 15;

  // ============ RECOMMENDATIONS - FIXED TEXT WRAPPING ============
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(13);
  pdf.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  pdf.text(t.treatmentRecommendations, 14, yPos);
  
  pdf.setDrawColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
  pdf.setLineWidth(2);
  pdf.line(14, yPos + 1.5, 85, yPos + 1.5);
  
  yPos += 8;

  const recommendations = result.recommendations || [];
  const displayRecs = recommendations.slice(0, 4);

  displayRecs.forEach((rec) => {
    // Green bullet
    pdf.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
    pdf.circle(17, yPos - 1.5, 1.5, 'F');

    // CONSISTENT font for all recommendations
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8.5);
    pdf.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    
    // No watermark now, so use full width
    const textStartX = 21;
    const rightMargin = 20; // Normal margin (no watermark)
    const availableWidth = pageWidth - textStartX - rightMargin;
    
    const lines = pdf.splitTextToSize(rec, availableWidth);
    const displayLines = lines.slice(0, 2); // Max 2 lines
    pdf.text(displayLines, textStartX, yPos);
    
    // Consistent spacing between all items
    yPos += displayLines.length * 4.5 + 2;
  });

  // ============ PREVENTION BOX ============
  yPos += 10;

  pdf.setFillColor(COLORS.yellow[0], COLORS.yellow[1], COLORS.yellow[2]);
  pdf.roundedRect(14, yPos, pageWidth - 28, 37, 3, 3, 'F');
  
  pdf.setDrawColor(COLORS.orange[0], COLORS.orange[1], COLORS.orange[2]);
  pdf.setLineWidth(1.2);
  pdf.roundedRect(14, yPos, pageWidth - 28, 37, 3, 3, 'S');

  yPos += 9;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(180, 83, 9);
  pdf.text(t.prevention, 18, yPos);

  yPos += 7;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8.5);
  pdf.setTextColor(120, 53, 15);
  
  const tips = [
    'Regular monitoring: Check plants daily for early symptoms',
    'Proper spacing: Ensure adequate air circulation between plants',
    'Hygiene: Remove and dispose of infected plant material properly',
    'Rotation: Practice crop rotation to prevent disease buildup',
  ];

  tips.forEach(tip => {
    const tipWidth = pageWidth - 40;
    const tipLines = pdf.splitTextToSize(tip, tipWidth);
    pdf.text(tipLines, 18, yPos);
    yPos += tipLines.length * 4.5 + 0.5;
  });

  // ============ FOOTER ============
  const footerY = pageHeight - 14;
  
  pdf.setFillColor(249, 250, 251);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (pdf as any).setGState(new (pdf as any).GState({ opacity: 0.95 }));
  pdf.rect(0, footerY - 6, pageWidth, 20, 'F');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (pdf as any).setGState(new (pdf as any).GState({ opacity: 1 }));
  
  pdf.setDrawColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.setLineWidth(0.5);
  pdf.line(14, footerY - 6, pageWidth - 14, footerY - 6);

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  pdf.text('© 2025 AgriSakhi', 14, footerY);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  pdf.text('AI-Powered Plant Disease Detection - For assistance: agrisakhi.com', 14, footerY + 4);
  
  // Page number
  pdf.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  pdf.circle(pageWidth - 17, footerY - 0.5, 4.5, 'F');
  pdf.setTextColor(COLORS.white[0], COLORS.white[1], COLORS.white[2]);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.text('1', pageWidth - 18.5, footerY + 2);
  
  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(6.5);
  pdf.setTextColor(COLORS.textLight[0], COLORS.textLight[1], COLORS.textLight[2]);
  const disclaimer = t.disclaimerText;
  pdf.text(disclaimer, 14, footerY + 8);

  // ============ SAVE ============
  const fileName = `AgriSakhi_Report_${diseaseName.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  pdf.save(fileName);
}

// GState polyfill
declare module 'jspdf' {
  interface jsPDF {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    GState(options: { opacity: number }): any;
  }
}
